---
title: Bayesian data analysis -- reading instructions 9
---

# Chapter 9

Outline of the chapter 9

-   9.1 Context and basic steps (most important part)

-   9.2 Example

-   9.3 Multistage decision analysis (you may skip this example)

-   9.4 Hierarchical decision analysis (you may skip this example)

-   9.5 Personal vs. institutional decision analysis (important)

Find all the terms and symbols listed below. When reading the chapter,
write down questions related to things unclear for you or things you
think might be unclear for others.

-   decision analysis

-   steps of Bayesian decision analysis 1--4 (p. 238)

-   decision

-   outcome

-   utility function

-   expected utility

-   decision tree

-   summarizing inference

-   model selection

-   individual decision problem

-   institutional decision problem

# Simpler examples

The lectures have simpler examples and also discuss some challenges in
selecting utilities or costs.

# Model selection as a decision problem

Chapter 7 discusses how model selection con be considered as a decision
problem.
