<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-09-23">

<title>Bayesian Data Analysis course - Aalto 2024 – Bayesian Data Analysis course</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Bayesian Data Analysis course</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Material</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Aalto2024.html" aria-current="page"> 
<span class="menu-text">Aalto 2024</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./BDA3_notes.html"> 
<span class="menu-text">BDA3 notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./assignments.html"> 
<span class="menu-text">Assignments</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./project.html"> 
<span class="menu-text">Project</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./demos.html"> 
<span class="menu-text">Demos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./FAQ.html"> 
<span class="menu-text">FAQ</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#book-bda3" id="toc-book-bda3" class="nav-link active" data-scroll-target="#book-bda3">Book: BDA3</a></li>
  <li><a href="#prerequisites" id="toc-prerequisites" class="nav-link" data-scroll-target="#prerequisites">Prerequisites</a></li>
  <li><a href="#communication-channels" id="toc-communication-channels" class="nav-link" data-scroll-target="#communication-channels">Communication channels</a></li>
  <li><a href="#assessment" id="toc-assessment" class="nav-link" data-scroll-target="#assessment">Assessment</a></li>
  <li><a href="#schedule-2024" id="toc-schedule-2024" class="nav-link" data-scroll-target="#schedule-2024">Schedule 2024</a>
  <ul class="collapse">
  <li><a href="#schedule-overview" id="toc-schedule-overview" class="nav-link" data-scroll-target="#schedule-overview">Schedule overview</a></li>
  <li><a href="#course-introduction-bda-3-ch-1-prerequisites-assignment" id="toc-course-introduction-bda-3-ch-1-prerequisites-assignment" class="nav-link" data-scroll-target="#course-introduction-bda-3-ch-1-prerequisites-assignment">1) Course introduction, BDA 3 Ch 1, prerequisites assignment</a></li>
  <li><a href="#bda3-ch-12-basics-of-bayesian-inference" id="toc-bda3-ch-12-basics-of-bayesian-inference" class="nav-link" data-scroll-target="#bda3-ch-12-basics-of-bayesian-inference">2) BDA3 Ch 1+2, basics of Bayesian inference</a></li>
  <li><a href="#bda3-ch-3-multidimensional-posterior" id="toc-bda3-ch-3-multidimensional-posterior" class="nav-link" data-scroll-target="#bda3-ch-3-multidimensional-posterior">3) BDA3 Ch 3, multidimensional posterior</a></li>
  <li><a href="#bda3-ch-10-monte-carlo" id="toc-bda3-ch-10-monte-carlo" class="nav-link" data-scroll-target="#bda3-ch-10-monte-carlo">4) BDA3 Ch 10, Monte Carlo</a></li>
  <li><a href="#bda3-ch-11-markov-chain-monte-carlo" id="toc-bda3-ch-11-markov-chain-monte-carlo" class="nav-link" data-scroll-target="#bda3-ch-11-markov-chain-monte-carlo">5) BDA3 Ch 11, Markov chain Monte Carlo</a></li>
  <li><a href="#bda3-ch-12-stan-hmc-ppl-stan" id="toc-bda3-ch-12-stan-hmc-ppl-stan" class="nav-link" data-scroll-target="#bda3-ch-12-stan-hmc-ppl-stan">6) BDA3 Ch 12 + Stan, HMC, PPL, Stan</a></li>
  <li><a href="#bda3-ch-5-hierarchical-models" id="toc-bda3-ch-5-hierarchical-models" class="nav-link" data-scroll-target="#bda3-ch-5-hierarchical-models">7) BDA3 Ch 5, hierarchical models</a></li>
  <li><a href="#bda3-ch-67-extra-material-model-checking-cross-validation" id="toc-bda3-ch-67-extra-material-model-checking-cross-validation" class="nav-link" data-scroll-target="#bda3-ch-67-extra-material-model-checking-cross-validation">8) BDA3 Ch 6+7 + extra material, model checking, cross-validation</a></li>
  <li><a href="#bda3-ch-7-extra-material-model-comparison-and-selection" id="toc-bda3-ch-7-extra-material-model-comparison-and-selection" class="nav-link" data-scroll-target="#bda3-ch-7-extra-material-model-comparison-and-selection">9) BDA3 Ch 7, extra material, model comparison and selection</a></li>
  <li><a href="#bda3-ch-9-decision-analysis-bda3-ch-4-laplace-approximation-and-asymptotics" id="toc-bda3-ch-9-decision-analysis-bda3-ch-4-laplace-approximation-and-asymptotics" class="nav-link" data-scroll-target="#bda3-ch-9-decision-analysis-bda3-ch-4-laplace-approximation-and-asymptotics">10) BDA3 Ch 9, decision analysis + BDA3 Ch 4 Laplace approximation and asymptotics</a></li>
  <li><a href="#variable-selection-with-projpred-project-presentation-example-extra" id="toc-variable-selection-with-projpred-project-presentation-example-extra" class="nav-link" data-scroll-target="#variable-selection-with-projpred-project-presentation-example-extra">11) Variable selection with projpred, project presentation example, extra</a></li>
  <li><a href="#tba" id="toc-tba" class="nav-link" data-scroll-target="#tba">12) TBA</a></li>
  <li><a href="#project-evaluation" id="toc-project-evaluation" class="nav-link" data-scroll-target="#project-evaluation">13) Project evaluation</a></li>
  </ul></li>
  <li><a href="#r" id="toc-r" class="nav-link" data-scroll-target="#r">R</a></li>
  <li><a href="#english-finnish-english-statistics-dictionary" id="toc-english-finnish-english-statistics-dictionary" class="nav-link" data-scroll-target="#english-finnish-english-statistics-dictionary">English-Finnish-English statistics dictionary</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Bayesian Data Analysis course - Aalto 2024</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 23, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>The 2024 course web pages have been updated. If you notice something that looks as old information from year 2023, please send a message in Zulip. A big change in the course is the reduced use of peergrading as the previously used system was shut down, which means also substantial changes in the assignments.</p>
<p><strong>Aalto 2024</strong> course can be taken online except for the final project presentation. The lectures will be given on campus, but recorded and the recording will be made available online after the lecture. If you are unable to register for the course at the moment in the Sisu, there is no need to email the lecturer. You can start taking the course and register before the end of the course. Sisu shows rooms on campus for the computer exercises, and you can come to ask questions on campus, but you can also ask in Zulip during the same times. You can choose which TA session to join each week separately, without a need to register for those sessions.</p>
<ul>
<li><a href="https://mycourses.aalto.fi/course/view.php?id=40722">MyCourses</a> is used for initial announcements, linking to Zulip, assignment quizzes, peergrading, and some questionnaires.</li>
<li>Most of the communication happens in the course chat (see below)</li>
<li><a href="https://www.aalto.fi/en/applications-instructions-and-guidelines/aalto-university-code-of-academic-integrity-and-handling-violations-thereof">Aalto University Code of Academic Integrity and Handling Violations Thereof</a></li>
<li>Use of AI is allowed on the course, but the most of the work needs to be made by the student, and you need to report whether you used AI and in which way you used them (See <a href="https://www.aalto.fi/en/services/guidance-for-the-use-of-artificial-intelligence-in-teaching-and-learning-at-aalto-university">points 5 and 6 in Aalto guidelines for use of AI in teaching</a>). We have tested some AI on the course topics and assignments and the output can be copy of existing text without attribution (ie plagiarism), vague or have mistakes, so you need to be careful when using such outputs.</li>
</ul>
<p>All the course material is available in a <a href="https://github.com/avehtari/BDA_course_Aalto">git repo</a> (and these pages are for easier navigation). All the material can be used in other courses. Text and videos licensed under CC-BY-NC 4.0. Code licensed under BSD-3.</p>
<p>The material will be updated during the course. Exercise instructions and slides will be updated at latest on Monday of the corresponding week. The updated material will appear on the web pages, or you can clone the repo and pull before checking new material. If you don’t want to learn git, you can download the latest <a href="https://github.com/avehtari/BDA_course_Aalto/archive/master.zip">zip file</a>.</p>
<section id="book-bda3" class="level2">
<h2 class="anchored" data-anchor-id="book-bda3">Book: BDA3</h2>
<div style="float:right;position: relative;">
<p><img src="bda_cover.png" class="img-fluid"></p>
</div>
<p><a href="https://users.aalto.fi/~ave/BDA3.pdf">The electronic version of the course book Bayesian Data Analysis, 3rd ed, by Andrew Gelman, John Carlin, Hal Stern, David Dunson, Aki Vehtari, and Donald Rubin</a> is available for non-commercial purposes. Hard copies are available from <a href="https://www.crcpress.com/Bayesian-Data-Analysis/Gelman-Carlin-Stern-Dunson-Vehtari-Rubin/p/book/9781439840955">the publisher</a> and many book stores. Aalto library has also copies. See also <a href="http://www.stat.columbia.edu/~gelman/book/">home page for the book</a>, <a href="http://www.stat.columbia.edu/~gelman/book/errata_bda3.txt">errata for the book</a>, and <a href="BDA3_notes.html">chapter notes</a>.</p>
</section>
<section id="prerequisites" class="level2">
<h2 class="anchored" data-anchor-id="prerequisites">Prerequisites</h2>
<ul>
<li>Basic terms of probability theory
<ul>
<li>probability, probability density, distribution</li>
<li>sum, product rule, and Bayes’ rule</li>
<li>expectation, mean, variance, median</li>
<li>in Finnish, see e.g.&nbsp;<a href="http://math.aalto.fi/~lleskela/LectureNotes003.html">Stokastiikka ja tilastollinen ajattelu</a></li>
<li>in English, see e.g.&nbsp;Wikipedia and <a href="https://ocw.mit.edu/courses/mathematics/18-05-introduction-to-probability-and-statistics-spring-2014/readings/">Introduction to probability and statistics</a></li>
</ul></li>
<li>Some algebra and calculus</li>
<li>Basic visualisation techniques (R or Python)
<ul>
<li>histogram, density plot, scatter plot</li>
<li>see e.g.&nbsp;<a href="demos.html#BDA_R_demos">BDA R demos</a></li>
<li>see e.g.&nbsp;<a href="demos.html#BDA_Python_demos">BDA Python demos</a></li>
</ul></li>
</ul>
<p>This course has been designed so that there is strong emphasis in computational aspects of Bayesian data analysis and using the latest computational tools. The project brings together the overall Bayesian workflow aspects.</p>
<p>If you find BDA3 too difficult to start with, I recommend</p>
<ul>
<li>For regression models, their connection to statistical testing and causal analysis see <a href="https://avehtari.github.io/ROS-Examples/">Gelman, Hill and Vehtari: “Regression and Other Stories”</a>.</li>
<li><a href="https://xcelab.net/rm/statistical-rethinking/">Richard McElreath: Statistical Rethinking, 2nd ed</a> book is easier than BDA3 and the 2nd ed is excellent. Statistical Rethinking doesn’t go as deep in some details, math, algorithms and programming as BDA course. Richard’s lecture videos of <a href="https://github.com/rmcelreath/statrethinking_winter2019">Statistical Rethinking: A Bayesian Course Using R and Stan</a> are highly recommended even if you are following BDA3.</li>
<li><a href="https://www.bayesrulesbook.com/">Johnson, Ott, and Dogucu: Bayes Rules! An Introduction to Applied Bayesian Modeling</a></li>
<li>For background prerequisites some students have found chapters 2, 4 and 5 in <a href="https://sites.google.com/site/doingbayesiandataanalysis/">Kruschke, “Doing Bayesian Data Analysis”</a> useful.</li>
</ul>
</section>
<section id="communication-channels" class="level2">
<h2 class="anchored" data-anchor-id="communication-channels">Communication channels</h2>
<ul>
<li><a href="https://mycourses.aalto.fi/course/view.php?id=40722">MyCourses</a> is used for some intial announcements, linking to Zulip and Peergrade, and some questionnaires.</li>
<li>The primary communication channel is the Zulip course chat (link in MyCourses, login with Aalto account)
<ul>
<li>Don’t ask via email or direct messages. By asking via common streams in the course chat, more eyes will see your question, it will get answered faster and it’s likely that other students benefit from the answer.</li>
<li>Login with Aalto account to the Zulip course chat. You can adjust the notifications in the settings.</li>
<li>If you have any questions, please ask in the public streams and get answers from course staff or other students (active students helping others will get bonus points).</li>
<li>In the chat system, we will have separate streams for each assignment and the project.</li>
<li>Stream <strong>#general</strong> can be used for any kind of general discussions and questions related to the course.</li>
<li>All important announcements will be posted to <strong>#announcements</strong> (no discussion on this stream).</li>
<li>Any kind of feedback is welcome on stream <strong>#feedback</strong>.</li>
<li>We have also streams <strong>#r</strong>, <strong>#python</strong>, and <strong>#stan</strong> for questions that are not specific to assignments or the project.</li>
<li>Stream <strong>#queue</strong> is used as a queue for getting help during <a href="assignments.html#TA_sessions">TA sessions</a>.</li>
<li>The lecturer and teaching assistants have names with “(staff)” or “(TA)” in the end of their names.</li>
</ul></li>
<li>A weekly lecture time on campus includes times for questions and answers</li>
<li>If you need one-to-one help, please take part in the <a href="assignments.html#TA_sessions">TA sessions</a> and ask there.</li>
<li>If you find errors in material, post in <strong>#feedback</strong> stream or <a href="https://github.com/avehtari/BDA_course_Aalto/issues">submit an issue in github</a>.</li>
</ul>
</section>
<section id="assessment" class="level2">
<h2 class="anchored" data-anchor-id="assessment">Assessment</h2>
<p><a href="assignments.html">Assignments</a> (40%), e-exam (10%), and a <a href="project.html">project work with presentation</a> (50%). Minimum of 50% of points must be obtained from each. You can get <a href="assignments.html#bonus">bonus points</a> from chat activity (e.g.&nbsp;helping other students and reporting typos in the material) and answering time usage questionnaries.</p>
</section>
<section id="schedule-2024" class="level2">
<h2 class="anchored" data-anchor-id="schedule-2024">Schedule 2024</h2>
<p>The course consists of 12 lectures, 9 assignments, a project work, and a project presentation in periods I and II. It’s good start reading the material for the next lecture and assignment while making the assignment related to the previous lecture. There are 9 assignments and a project work with presentation, and thus the assignments are not in one-to-one correspondence with the lectures. The schedule below lists the lectures and how they connect to the topics, book chapters and assignments.</p>
<section id="schedule-overview" class="level3">
<h3 class="anchored" data-anchor-id="schedule-overview">Schedule overview</h3>
<p>Here is an overview of the schedule. Scroll down the page to see detailed instructions for each block. When you are working on assignment related to previous lecture, it is good to start reading the book chapters relaed to the next lecture and assignment. The schedule links to 2023 lecture videos until couple hours after the 2024 lecture has been recorded.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: left;">Readings</th>
<th>Lectures</th>
<th>Assignment</th>
<th>Lecture Date</th>
<th>Assignment due date</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1. Introduction</td>
<td style="text-align: left;"><a href="BDA3_notes.html#ch1">BDA3 Chapter 1</a></td>
<td><a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=46a41a38-7414-40a9-a353-b1df00c97ba4">2024 Lecture 1.1 Introduction</a>, <br> <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=ebf8f909-7b2d-4e34-a127-b1df00ba8635">2024 Lecture 1.2 Course practicalities</a>, <br><a href="slides/BDA_lecture_1a.pdf">Slides 1.1</a>,<br> <a href="slides/BDA_lecture_1b.pdf">Slides 1.2</a></td>
<td><a href="https://avehtari.github.io/BDA_course_Aalto/assignments/assignment1.html">2024 Assignment 1</a></td>
<td>2024-09-02</td>
<td>2024-09-15</td>
</tr>
<tr class="even">
<td>2. Basics of Bayesian inference</td>
<td style="text-align: left;"><a href="BDA3_notes.html#ch1">BDA3 Chapter 1</a>, <br> <a href="BDA3_notes.html#ch2">BDA3 Chapter 2</a></td>
<td><a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=ed9cb7e6-a910-4afe-8659-b07a00bab594">2023 Lecture 2.1 (2024 recording failed)</a>, <br> <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=7e80ca10-0b36-424d-9f4e-b1ed00c3fa6b">2024 Lecture 2.2</a>, <br><a href="slides/BDA_lecture_2.pdf">Slides 2</a></td>
<td><a href="assignments/assignment2.html">Assignment 2</a></td>
<td>2024-09-16</td>
<td>2024-09-22</td>
</tr>
<tr class="odd">
<td>3. Multidimensional posterior</td>
<td style="text-align: left;"><a href="BDA3_notes.html#ch3">BDA3 Chapter 3</a></td>
<td><a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=802abb82-07a2-4b4e-a16b-b0820089d994">2023 Lecture 3.1</a>,<br> <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=c070e17c-ce4c-4a98-801c-b08200a5b22f">2023 Lecture 3.2</a><br><a href="slides/BDA_lecture_3.pdf">Slides 3</a></td>
<td><a href="assignments/assignment3.html">Old Assignment 3</a></td>
<td>2024-09-23</td>
<td>2024-09-29</td>
</tr>
<tr class="even">
<td>4. Monte Carlo</td>
<td style="text-align: left;"><a href="BDA3_notes.html#ch10">BDA3 Chapter 10</a></td>
<td><a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=d0a08786-0796-4e93-90a3-b08800b99601">2023 Lecture 4.1</a>,<br> <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=ad034e33-56da-4255-9f3a-b08800cbe37e">2023 Lecture 4.2</a>, <br><a href="slides/BDA_lecture_4.pdf">Slides 4</a></td>
<td><a href="assignments/assignment4.html">Old Assignment 4</a></td>
<td>2024-09-30</td>
<td>2024-10-06</td>
</tr>
<tr class="odd">
<td>5. Markov chain Monte Carlo</td>
<td style="text-align: left;"><a href="BDA3_notes.html#ch11">BDA3 Chapter 11</a></td>
<td><a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=279b3da6-efe6-44f7-b382-b08f00dd234b">2023 Lecture 5.1</a>, <br> <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=ff3d41ef-b1cc-42b3-8544-b08f00ca25b2">2023 Lecture 5.2</a>, <br><a href="slides/BDA_lecture_5.pdf">Slides 5</a></td>
<td><a href="assignments/assignment5.html">Old Assignment 5</a></td>
<td>2024-10-07</td>
<td>2024-10-13</td>
</tr>
<tr class="even">
<td>6. Stan, HMC, PPL</td>
<td style="text-align: left;"><a href="BDA3_notes.html#ch12">BDA3 Chapter 12</a> + <a href="index.html#stan">extra material on Stan</a></td>
<td><a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=80a36d3a-d67c-4534-a7ef-b09600b9f338">2023 Lecture 6.1</a>, <br><a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=65bf5b2b-0a4e-4cae-ba26-b09600cb6222">2023 Lecture 6.2</a>, <br><a href="slides/BDA_lecture_6.pdf">Slides 6</a></td>
<td><a href="assignments/assignment6.html">Old Assignment 6</a></td>
<td>2024-10-14</td>
<td>2024-10-27</td>
</tr>
<tr class="odd">
<td>7. Hierarchical models and exchangeability</td>
<td style="text-align: left;"><a href="BDA3_notes.html#ch5">BDA3 Chapter 5</a></td>
<td><a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=c1014690-1133-4232-ad0f-b0a400ba228d">2023 Lecture 7.1</a>, <br> <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=196c3a91-3ba2-4469-ab15-b0a400ca6074">2023 Lecture 7.2</a>,<br> <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=8f0158f9-6abf-4ada-bdb7-af3800d139de">2022 Project info</a>, <br><a href="slides/BDA_lecture_7.pdf">Slides 7</a></td>
<td><a href="assignments/assignment7.html">Old Assignment 7</a></td>
<td>2024-10-28</td>
<td>2024-11-03</td>
</tr>
<tr class="even">
<td>8. Model checking &amp; cross-validation</td>
<td style="text-align: left;"><a href="BDA3_notes.html#ch6">BDA3 Chapter 6</a>, <a href="BDA3_notes.html#ch7">BDA3 Chapter 7</a>, <a href="https://doi.org/10.1111/rssa.12378">Visualization in Bayesian workflow</a>, <a href="https://arxiv.org/abs/1507.04544">Practical Bayesian cross-validation</a></td>
<td><a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=785ece8a-16ef-4f64-8134-b0ab00cbd1e8">2023 Lecture 8.1</a>, <br> <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=456afda7-0e6d-4903-b0df-b0ab00da8f1e">2023 Lecture 8.2</a>, <br><a href="slides/BDA_lecture_8a.pdf">Slides 8a</a>,<a href="slides/BDA_lecture_8b.pdf">Slides 8b</a></td>
<td>Start project work</td>
<td>2024-11-04</td>
<td>N/A</td>
</tr>
<tr class="odd">
<td>9. Model comparison, selection, and hypothesis testing</td>
<td style="text-align: left;"><a href="BDA3_notes.html#ch7">BDA3 Chapter 7 (not 7.2 and 7.3)</a>, <br> <a href="https://arxiv.org/abs/1507.04544">Practical Bayesian cross-validation</a></td>
<td><a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=a4961b5a-7e42-4603-8aaf-b0b200ca6295">2023 Lecture 9.1</a>, <br> <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=a4796c79-eab2-436e-b55f-b0b200dac7ce">2023 Lecture 9.2</a>, <br><a href="slides/BDA_lecture_9.pdf">Slides 9</a></td>
<td><a href="assignments/assignment8.html">Old Assignment 8</a></td>
<td>2024-11-11</td>
<td>2024-11-10</td>
</tr>
<tr class="even">
<td>10. Decision analysis</td>
<td style="text-align: left;"><a href="BDA3_notes.html#ch9">BDA3 Chapter 9</a></td>
<td><a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=c4ab903a-bc22-416f-99c8-b0b900c9f3f7">2023 Lecture 10.1</a>, <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=2a6d7c79-7797-4a6d-8efa-b0b900d8f24c">2023 Lecture 10.2</a>, <br><a href="slides/BDA_lecture_10a.pdf">Slides 10a</a>, <a href="slides/BDA_lecture_10b.pdf">Slides 10b</a></td>
<td><a href="assignments/assignment9.html">Old Assignment 9</a></td>
<td>2024-11-18</td>
<td>2024-11-17</td>
</tr>
<tr class="odd">
<td>11. Variable selectio with projpred, project presentation example</td>
<td style="text-align: left;"><a href="BDA3_notes.html#ch4">BDA3 Chapter 4</a></td>
<td><a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=7ef70bc8-122b-4e86-80fa-b0c000cb5511">2023 Lecture 11.1</a>, <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=a2b3bcb8-240e-4e6c-b90e-b0c000d92770">2023 Lecture 11.2</a>, <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=ae634732-1f4e-4568-8529-b0c000e0f153">2023 Lecture 11.3</a>, <br><a href="slides/BDA_lecture_11a.pdf">Slides 11a</a>, <a href="project_work/BDA_presentation_example.pdf">Slides Project Presentation</a>, <a href="slides/slides_extra.pdf">Slides 11 extra</a></td>
<td>Project work</td>
<td>2024-11-25</td>
<td>N/A</td>
</tr>
<tr class="even">
<td>12. TBA</td>
<td style="text-align: left;"></td>
<td>Optional: <br> <br> <br></td>
<td>Project work</td>
<td>2024-12-02</td>
<td>N/A</td>
</tr>
<tr class="odd">
<td>13. Project evaluation</td>
<td style="text-align: left;"></td>
<td></td>
<td></td>
<td>Project presentations: 9.-13.12.</td>
<td>Evaluation week</td>
</tr>
</tbody>
</table>
</section>
<section id="course-introduction-bda-3-ch-1-prerequisites-assignment" class="level3">
<h3 class="anchored" data-anchor-id="course-introduction-bda-3-ch-1-prerequisites-assignment">1) Course introduction, BDA 3 Ch 1, prerequisites assignment</h3>
<p>Course practicalities, material, assignments, project work, peergrading, QA sessions, TA sessions, prerequisites, chat, etc.</p>
<ul>
<li>Login with Aalto account to the Zulip course chat with link in MyCourses</li>
<li>Introduction/practicalities <strong>lecture Monday 2024-09-02 14:15-16</strong>, hall C, Otakaari 1**<br>
<ul>
<li><a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Sessions/List.aspx?folderID=b6f169ef-a8b4-4a04-983b-b1df009838f8">2024 Lecture videos 1.1 and 1.2 in Panopto</a></li>
<li><a href="slides/BDA_lecture_1a.pdf">Slides 1.1</a>, <a href="slides/BDA_lecture_1b.pdf">Slides 1.2</a></li>
</ul></li>
<li>Read BDA3 Chapter 1
<ul>
<li>start with <a href="BDA3_notes.html#ch1">reading instructions for Chapter 1</a> and afterwards read the additional comments in the same document</li>
</ul></li>
<li>There are no R demos for Chapter 1</li>
<li>Make and submit <a href="https://avehtari.github.io/BDA_course_Aalto/assignments/assignment1.html">2024 Assignment 1</a>. <strong>Deadline Sunday 2024-09-15 23:59</strong>
<ul>
<li>We highly recommend to submit all assignments Friday before 3pm so that you can get TA help before submission. As the course has students who work weekdays (e.g.&nbsp;FiTech students), the late submission until Sunday night is allowed, but we can’t provide support during the weekends.</li>
<li>this assignment checks that you have sufficient prerequisite skills (basic probability calculus, and R or Python)</li>
<li><a href="assignments.html">General information about assignments</a>
<ul>
<li><a href="https://github.com/avehtari/BDA_course_Aalto/tree/master/templates/">R markdown template for assignments</a></li>
<li><a href="FAQ.html">FAQ for the assignments</a> has solutions to commonly asked questions related RStudio setup, errors during package installations, etc.</li>
</ul></li>
</ul></li>
<li>Get help in TA sessions 2024-09-04 14-16, Y342a, Otakaari 1 2024-09-05 12-14, Y429c-d, Otakaari 1
<ul>
<li>in Sisu these are marked as exercise sessions, but we call them TA sessions</li>
<li>these are optional and you can choose which one to join</li>
<li>see more info about <a href="assignments.html#TA_sessions">TA sessions</a></li>
</ul></li>
<li>Highly recommended, but optional: Make BDA3 exercises 1.1-1.4, 1.6-1.8 (<a href="http://www.stat.columbia.edu/~gelman/book/solutions3.pdf">model solutions available for 1.1-1.6</a>)</li>
<li>Start reading Chapters 1+2, see instructions below</li>
</ul>
</section>
<section id="bda3-ch-12-basics-of-bayesian-inference" class="level3">
<h3 class="anchored" data-anchor-id="bda3-ch-12-basics-of-bayesian-inference">2) BDA3 Ch 1+2, basics of Bayesian inference</h3>
<p>BDA3 Chapters 1+2, basics of Bayesian inference, observation model, likelihood, posterior and binomial model, predictive distribution and benefit of integration, priors and prior information, and one parameter normal model.</p>
<ul>
<li>Read BDA3 Chapter 2
<ul>
<li>see <a href="BDA3_notes.html#ch2">reading instructions for Chapter 2</a></li>
</ul></li>
<li><strong>Lecture Monday 2024-09-16 14:15-16, hall T1, CS building</strong>
<ul>
<li><a href="slides/BDA_lecture_2.pdf">Slides 2</a></li>
<li>Videos: <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=ed9cb7e6-a910-4afe-8659-b07a00bab594">2023 Lecture 2.1 (2024 recording failed)</a>, <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=7e80ca10-0b36-424d-9f4e-b1ed00c3fa6b">2024 Lecture 2.2</a> on basics of Bayesian inference, observation model, likelihood, posterior and binomial model, predictive distribution and benefit of integration, priors and prior information, and one parameter normal model. BDA3 Ch 1+2.</li>
</ul></li>
<li>Read <a href="BDA3_notes.html#ch2">the additional comments for Chapter 2</a></li>
<li>Check <a href="demos.html#BDA_R_demos">R demos</a> or <a href="demos.html#BDA_Python_demos">Python demos</a> for Chapter 2</li>
<li>Make and submit <a href="assignments/assignment2.html">Assignment 2</a>. <strong>Deadline Sunday 2024-09-22 23:59</strong>
<ul>
<li><a href="assignments.html#TA_sessions">TA sessions</a> 2024-09-18 14-16, Y342a, Otakaari 1 2024-09-19 12-14, Y429c-d, Otakaari 1</li>
</ul></li>
<li>Highly recommended, but optional: Make BDA3 exercises 2.1-2.5, 2.8, 2.9, 2.14, 2.17, 2.22 (<a href="http://www.stat.columbia.edu/~gelman/book/solutions3.pdf">model solutions available for 2.1-2.5, 2.7-2.13, 2.16, 2.17, 2.20</a>, and 2.14 is in course slides)</li>
<li>Start reading Chapter 3, see instructions below</li>
</ul>
</section>
<section id="bda3-ch-3-multidimensional-posterior" class="level3">
<h3 class="anchored" data-anchor-id="bda3-ch-3-multidimensional-posterior">3) BDA3 Ch 3, multidimensional posterior</h3>
<p>Multiparameter models, joint, marginal and conditional distribution, normal model, bioassay example, grid sampling and grid evaluation. BDA3 Ch 3.</p>
<ul>
<li>Read BDA3 Chapter 3
<ul>
<li>see <a href="BDA3_notes.html#ch3">reading instructions for Chapter 3</a></li>
</ul></li>
<li><strong>Lecture Monday 2024-09-23. 14:15-16, hall T1, CS building</strong>
<ul>
<li><a href="slides/BDA_lecture_3.pdf">Slides 3</a></li>
<li>Videos: <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=802abb82-07a2-4b4e-a16b-b0820089d994">2023 Lecture 3.1</a> <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=c070e17c-ce4c-4a98-801c-b08200a5b22f">2023 Lecture 3.2</a> on multiparameter models, joint, marginal and conditional distribution, normal model, bioassay example, grid sampling and grid evaluation. BDA3 Ch 3.</li>
</ul></li>
<li>Read <a href="BDA3_notes.html#ch3">the additional comments for Chapter 3</a></li>
<li>Check <a href="demos.html#BDA_R_demos">R demos</a> or <a href="demos.html#BDA_Python_demos">Python demos</a> for Chapter 3</li>
<li>Make and submit <a href="assignments/assignment3.html">Old Assignment 3</a>. <strong>Deadline Sunday 2024-09-29 23:59</strong></li>
<li><a href="assignments.html#TA_sessions">TA sessions</a> 2024-09-25 14-16, 2024-09-26 12-14,</li>
<li>Highly recommended, but optional: Make BDA3 exercises 3.2, 3.3, 3.9 (<a href="http://www.stat.columbia.edu/~gelman/book/solutions3.pdf">model solutions available for 3.1-3.3, 3.5, 3.9, 3.10</a>)</li>
<li>Start reading Chapter 10, see instructions below</li>
</ul>
</section>
<section id="bda3-ch-10-monte-carlo" class="level3">
<h3 class="anchored" data-anchor-id="bda3-ch-10-monte-carlo">4) BDA3 Ch 10, Monte Carlo</h3>
<p>Numerical issues, Monte Carlo, how many simulation draws are needed, how many digits to report, direct simulation, curse of dimensionality, rejection sampling, and importance sampling. BDA3 Ch 10.</p>
<ul>
<li>Read BDA3 Chapter 10
<ul>
<li>see <a href="BDA3_notes.html#ch10">reading instructions for Chapter 10</a></li>
</ul></li>
<li><strong>Lecture Monday 2024-09-30 14:15-16, hall T1, CS building</strong>
<ul>
<li><a href="slides/BDA_lecture_4.pdf">Slides 4</a></li>
<li>Videos: <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=d0a08786-0796-4e93-90a3-b08800b99601">2023 Lecture 4.1</a> on numerical issues, Monte Carlo, how many simulation draws are needed, how many digits to report, and <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=ad034e33-56da-4255-9f3a-b08800cbe37e">2023 Lecture 4.2</a> on direct simulation, curse of dimensionality, rejection sampling, and importance sampling. BDA3 Ch 10.</li>
</ul></li>
<li>Read <a href="BDA3_notes.html#ch10">the additional comments for Chapter 10</a></li>
<li>Check <a href="demos.html#BDA_R_demos">R demos</a> or <a href="demos.html#BDA_Python_demos">Python demos</a> for Chapter 10</li>
<li>Make and submit <a href="assignments/assignment4.html">Old Assignment 4</a>. <strong>Deadline Sunday 2024-10-06 23:59</strong></li>
<li><a href="assignments.html#TA_sessions">TA sessions</a> 2024-10-02 14-16, 2024-10-03 12-14,</li>
<li>Highly recommended, but optional: Make BDA3 exercises 10.1, 10.2 (<a href="http://www.stat.columbia.edu/~gelman/book/solutions3.pdf">model solution available for 10.4</a>)</li>
<li>Start reading Chapter 11, see instructions below</li>
</ul>
</section>
<section id="bda3-ch-11-markov-chain-monte-carlo" class="level3">
<h3 class="anchored" data-anchor-id="bda3-ch-11-markov-chain-monte-carlo">5) BDA3 Ch 11, Markov chain Monte Carlo</h3>
<p>Markov chain Monte Carlo, Gibbs sampling, Metropolis algorithm, warm-up, convergence diagnostics, R-hat, and effective sample size. BDA3 Ch 11.</p>
<ul>
<li>Read BDA3 Chapter 11
<ul>
<li>see <a href="BDA3_notes.html#ch11">reading instructions for Chapter 11</a></li>
</ul></li>
<li><strong>Lecture Monday 2024-10-07 14:15-16, hall T1, CS building</strong>
<ul>
<li><a href="slides/BDA_lecture_5.pdf">Slides 5</a></li>
<li>Videos: <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=279b3da6-efe6-44f7-b382-b08f00dd234b">2023 Lecture 5.1</a> on Markov chain Monte Carlo, Gibbs sampling, Metropolis algorithm, and <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=ff3d41ef-b1cc-42b3-8544-b08f00ca25b2">2023 Lecture 5.2</a> on warm-up, convergence diagnostics, R-hat, and effective sample size.</li>
</ul></li>
<li>Read <a href="BDA3_notes.html#ch11">the additional comments for Chapter 11</a></li>
<li>Check <a href="demos.html#BDA_R_demos">R demos</a> or <a href="demos.html#BDA_Python_demos">Python demos</a> for Chapter 11</li>
<li>Make and submit <a href="assignments/assignment5.html">Old Assignment 5</a>. <strong>Deadline Sunday 2024-10-13 23:59</strong></li>
<li><a href="assignments.html#TA_sessions">TA sessions</a> 2024-10-09 14-16, 2024-10-10 12-14,</li>
<li>Highly recommended, but optional: Make BDA3 exercise 11.1 (<a href="http://www.stat.columbia.edu/~gelman/book/solutions3.pdf">model solution available for 11.1</a>)</li>
<li>Start reading Chapter 12 + Stan material, see instructions below</li>
</ul>
</section>
<section id="bda3-ch-12-stan-hmc-ppl-stan" class="level3">
<h3 class="anchored" data-anchor-id="bda3-ch-12-stan-hmc-ppl-stan">6) BDA3 Ch 12 + Stan, HMC, PPL, Stan</h3>
<p>HMC, NUTS, dynamic HMC and HMC specific convergence diagnostics, probabilistic programming and Stan. BDA3 Ch 12 + <a href="index.html#stan">extra material</a></p>
<ul>
<li>Read BDA3 Chapter 12
<ul>
<li>see <a href="BDA3_notes.html#ch12">reading instructions for Chapter 12</a></li>
</ul></li>
<li><strong>Lecture Monday 2024-10-14 14:15-16, hall T1, CS building</strong>
<ul>
<li><a href="slides/BDA_lecture_6.pdf">Slides 6</a></li>
<li>Videos: <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=80a36d3a-d67c-4534-a7ef-b09600b9f338">2022 Lecture 6.1</a> on HMC, NUTS, dynamic HMC and HMC specific convergence diagnostics, and <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=65bf5b2b-0a4e-4cae-ba26-b09600cb6222">2022 Lecture 6.2</a> on probabilistic programming and Stan. BDA3 Ch 12 + <a href="#stan">extra material</a>.</li>
<li>Optional: <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=f4b61f2a-4a94-43f7-828c-ac460144f64f">Stan Extra introduction recorded 2020</a> Golf putting example, main features of Stan, benefits of probabilistic programming, and comparison to some other software.</li>
</ul></li>
<li>Read <a href="BDA3_notes.html#ch12">the additional comments for Chapter 12</a></li>
<li>Read <a href="http://www.stat.columbia.edu/~gelman/research/published/Stan-paper-aug-2015.pdf">Stan introduction article</a></li>
<li>Check <a href="demos.html#BDA_R_demos">R demos</a> for RStan or <a href="demos.html#BDA_Python_demos">Python demos</a> for PyStan</li>
<li>Additional material for Stan:
<ul>
<li><a href="https://mc-stan.org/users/documentation/">Documentation</a></li>
<li><a href="https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started">RStan installation</a></li>
<li><a href="https://pystan.readthedocs.io/en/latest/getting_started.html">PyStan installation</a></li>
<li>Basics of Bayesian inference and Stan, Jonah Gabry &amp; Lauren Kennedy <a href="https://www.youtube.com/watch?v=ZRpo41l02KQ&amp;t=8s&amp;list=PLuwyh42iHquU4hUBQs20hkBsKSMrp6H0J&amp;index=6">Part 1</a> and <a href="https://www.youtube.com/watch?v=6cc4N1vT8pk&amp;t=0s&amp;list=PLuwyh42iHquU4hUBQs20hkBsKSMrp6H0J&amp;index=7">Part 2</a></li>
</ul></li>
<li>Make and submit <a href="assignments/assignment6.html">Old Assignment 6</a>. <strong>DeadlineSunday 2024-10-27 23:59</strong> (two weeks for this assignment)</li>
<li><a href="assignments.html#TA_sessions">TA sessions</a> 2024-10-16 14-16, 2024-10-17 12-14,</li>
<li>Start reading Chapter 5 + Stan material, see instructions below</li>
</ul>
</section>
<section id="bda3-ch-5-hierarchical-models" class="level3">
<h3 class="anchored" data-anchor-id="bda3-ch-5-hierarchical-models">7) BDA3 Ch 5, hierarchical models</h3>
<p>Hierarchical models and exchangeability. BDA3 Ch 5.</p>
<ul>
<li>Read BDA3 Chapter 5
<ul>
<li>see <a href="BDA3_notes.html#ch5">reading instructions for Chapter 5</a></li>
</ul></li>
<li><strong>Lecture Monday 2024-10-28 14:15-16, hall T2, CS building</strong>
<ul>
<li><a href="slides/BDA_lecture_7.pdf">Slides 7</a></li>
<li>Videos: <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=c1014690-1133-4232-ad0f-b0a400ba228d">2023 Lecture 7.1</a> on hierarchical models, <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=196c3a91-3ba2-4469-ab15-b0a400ca6074">2023 Lecture 7.2</a> on exchangeability.</li>
</ul></li>
<li>Read <a href="BDA3_notes.html#ch5">the additional comments for Chapter 5</a></li>
<li>Check <a href="demos.html#BDA_R_demos">R demos</a> or <a href="demos.html#BDA_Python_demos">Python demos</a> for Chapter 5</li>
<li>Make and submit <a href="assignments/assignment7.html">Old Assignment 7</a>. <strong>Deadline Sunday 2024-11-03 23:59</strong> (two weeks for this assignment)</li>
<li><a href="assignments.html#TA_sessions">TA sessions</a> 2024-10-30 14-16, 2024-10-31 12-14,</li>
<li>Highly recommended, but optional: Make BDA3 exercises 5.1 and 5.2 (<a href="http://www.stat.columbia.edu/~gelman/book/solutions3.pdf">model solution available for 5.3-5.5, 5.7-5.12</a>)</li>
<li>Start reading Chapters 6-7 and additional material, see instructions below.</li>
</ul>
</section>
<section id="bda3-ch-67-extra-material-model-checking-cross-validation" class="level3">
<h3 class="anchored" data-anchor-id="bda3-ch-67-extra-material-model-checking-cross-validation">8) BDA3 Ch 6+7 + extra material, model checking, cross-validation</h3>
<p>Model checking and cross-validation.</p>
<ul>
<li>Read BDA3 Chapters 6 and 7 (skip 7.2 and 7.3)
<ul>
<li>see <a href="BDA3_notes.html#ch6">reading instructions for Chapter 6</a> and <a href="BDA3_notes.html#ch7">Chapter 7</a></li>
</ul></li>
<li>Read <a href="https://doi.org/10.1111/rssa.12378">Visualization in Bayesian workflow</a>
<ul>
<li>more about workflow and examples of prior predictive checking and LOO-CV probability integral transformations</li>
</ul></li>
<li>Read <a href="https://arxiv.org/abs/1507.04544">Practical Bayesian model evaluation using leave-one-out cross-validation and WAIC</a> (<a href="https://doi.org/10.1007/s11222-016-9696-4">Journal link</a>)
<ul>
<li>replaces BDA3 Sections 7.2 and 7.3 on cross-validation</li>
</ul></li>
<li><strong>Lecture Monday 2024-11-04 14:15-16, hall T2, CS building</strong>
<ul>
<li><a href="slides/BDA_lecture_8a.pdf">Slides 8a</a>, <a href="slides/BDA_lecture_8b.pdf">Slides 8b</a></li>
<li>Videos: <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=785ece8a-16ef-4f64-8134-b0ab00cbd1e8">2022 Lecture 8.1</a> on model checking, and <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=456afda7-0e6d-4903-b0df-b0ab00da8f1e">2023 Lecture 8.2</a> on cross-validation part 1. BDA3 Ch 6-7 + extra material.</li>
</ul></li>
<li>Read <a href="BDA3_notes.html#ch6">the additional comments for Chapter 6</a> and <a href="BDA3_notes.html#ch7">Chapter 7</a></li>
<li>Check <a href="demos.html#BDA_R_demos">R demos</a> or <a href="demos.html#BDA_Python_demos">Python demos</a> for Chapter 6</li>
<li>Additional reading material
<ul>
<li><a href="https://users.aalto.fi/~ave/CV-FAQ.html">Cross-validation FAQ</a></li>
</ul></li>
<li>No new assignment in this block</li>
<li>Start <a href="./project.html">the project work</a></li>
<li><a href="assignments.html#TA_sessions">TA sessions</a> 2024-11-06 14-16, 2024-11-07 12-14,</li>
<li>Highly recommended, but optional: Make BDA3 exercise 6.1 (<a href="http://www.stat.columbia.edu/~gelman/book/solutions3.pdf">model solution available for 6.1, 6.5-6.7</a>)</li>
</ul>
</section>
<section id="bda3-ch-7-extra-material-model-comparison-and-selection" class="level3">
<h3 class="anchored" data-anchor-id="bda3-ch-7-extra-material-model-comparison-and-selection">9) BDA3 Ch 7, extra material, model comparison and selection</h3>
<p>PSIS-LOO, K-fold-CV, model comparison and selection. Extra lecture on variable selection with projection predictive variable selection.</p>
<ul>
<li>Read Chapter 7 (no 7.2 and 7.3)
<ul>
<li>see <a href="BDA3_notes.html#ch7">reading instructions for Chapter 7</a></li>
</ul></li>
<li>Read <a href="https://arxiv.org/abs/1507.04544">Practical Bayesian model evaluation using leave-one-out cross-validation and WAIC</a> (<a href="https://doi.org/10.1007/s11222-016-9696-4">Journal link</a>)
<ul>
<li>replaces BDA3 Sections 7.2 and 7.3 on cross-validation</li>
</ul></li>
<li><strong>Lecture Monday 2024-11-11 14:15-16, hall T2, CS building</strong>
<ul>
<li><a href="slides/BDA_lecture_9.pdf">Slides 9</a></li>
<li>Videos: <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=a4961b5a-7e42-4603-8aaf-b0b200ca6295">2023 Lecture 9.1</a> and <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=a4796c79-eab2-436e-b55f-b0b200dac7ce">2023 Lecture 9.2</a> on model comparison, selection, and hypothesis testing.</li>
</ul></li>
<li>Additional reading material
<ul>
<li><a href="https://users.aalto.fi/~ave/CV-FAQ.html">CV FAQ</a></li>
</ul></li>
<li>Make and submit <a href="assignments/assignment8.html">Old Assignment 8</a>. <strong>Sunday 2024-11-10 23:59</strong></li>
<li><a href="assignments.html#TA_sessions">TA sessions</a> 2024-11-13 14-16, 2024-11-14 12-14,</li>
<li>Start reading Chapter 9, see instructions below.</li>
</ul>
</section>
<section id="bda3-ch-9-decision-analysis-bda3-ch-4-laplace-approximation-and-asymptotics" class="level3">
<h3 class="anchored" data-anchor-id="bda3-ch-9-decision-analysis-bda3-ch-4-laplace-approximation-and-asymptotics">10) BDA3 Ch 9, decision analysis + BDA3 Ch 4 Laplace approximation and asymptotics</h3>
<p>Decision analysis. BDA3 Ch 9. + Laplace approximation and asymptotics. BDA Ch 4.</p>
<ul>
<li>Read Chapter 9 and 4
<ul>
<li>see <a href="BDA3_notes.html#ch9">reading instructions for Chapter 9</a></li>
<li>see <a href="BDA3_notes.html#ch4">reading instructions for Chapter 4</a></li>
</ul></li>
<li><strong>Lecture Monday 2024-11-18 14:15-16, hall T2, CS building</strong>
<ul>
<li><a href="slides/BDA_lecture_10a.pdf">Slides 10a</a>, <a href="slides/BDA_lecture_10b.pdf">Slides 10b</a></li>
<li>Videos: <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=c4ab903a-bc22-416f-99c8-b0b900c9f3f7">2023 Lecture 10.1</a> on decision analysis. BDA3 Ch 9, and <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=2a6d7c79-7797-4a6d-8efa-b0b900d8f24c">2023 Lecture 10.2</a> on Laplace approximation, and asymptotics, BDA3 Ch 4.</li>
</ul></li>
<li>Make and submit <a href="assignments/assignment9.html">Old Assignment 9</a>. <strong>Sunday 2024-11-17 23:59</strong></li>
<li><a href="assignments.html#TA_sessions">TA sessions</a> 2024-11-20 14-16, 2024-11-21 12-14,</li>
<li>Start reading Chapter 4, see instructions below.</li>
</ul>
</section>
<section id="variable-selection-with-projpred-project-presentation-example-extra" class="level3">
<h3 class="anchored" data-anchor-id="variable-selection-with-projpred-project-presentation-example-extra">11) Variable selection with projpred, project presentation example, extra</h3>
<ul>
<li><strong>Lecture Monday 2024-11-25 14:15-16, hall T2, CS building</strong>
<ul>
<li><a href="slides/BDA_lecture_11a.pdf">Slides 11a</a>, <a href="project_work/BDA_presentation_example.pdf">Slides Project Presentation</a>, <a href="slides/slides_extra.pdf">Slides 11 extra</a></li>
<li>Videos: <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=7ef70bc8-122b-4e86-80fa-b0c000cb5511">2023 Lecture 11.1</a> on variable selecion with projpred, <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=a2b3bcb8-240e-4e6c-b90e-b0c000d92770">2023 Lecture 11.2</a> on project presentations, <a href="https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=ae634732-1f4e-4568-8529-b0c000e0f153">2023 Lecture 11.3</a> on rest of BDA3, ROS, and Bayesian Workflow</li>
</ul></li>
<li>No new assignment. Work on project. TAs help with projects.</li>
<li><a href="assignments.html#TA_sessions">TA sessions</a> 2024-11-27 14-16, 2024-11-28 12-14,</li>
</ul>
</section>
<section id="tba" class="level3">
<h3 class="anchored" data-anchor-id="tba">12) TBA</h3>
<ul>
<li><strong>Lecture Monday 2024-12-02 14:15-16, hall T2, CS building</strong>
<ul>
<li><a href="slides/BDA_lecture_12.pdf">Slides 12</a></li>
</ul></li>
<li>TBA</li>
<li>Work on project. TAs help with projects. <strong>Project deadline 1.12. 23:59</strong></li>
<li><a href="assignments.html#TA_sessions">TA sessions</a> 2024-12-04 14-16, 2024-12-05 12-14,</li>
</ul>
</section>
<section id="project-evaluation" class="level3">
<h3 class="anchored" data-anchor-id="project-evaluation">13) Project evaluation</h3>
<ul>
<li>Project report deadline 1.12. 23:59 (submit to peergrade).
<ul>
<li>Review project reports done by your peers before 6.12. 23:59, and reflect on your feedback.</li>
</ul></li>
<li>Project presentations 9.-13.12. (evaluation week)</li>
</ul>
</section>
</section>
<section id="r" class="level2">
<h2 class="anchored" data-anchor-id="r">R</h2>
<p>R is used in the course as there are more packages for Stan and statistical analysis. Unless you are already experienced and have figured out your preferred way to work with R, we recommend</p>
<ul>
<li><a href="FAQ.html#How_to_use_R_and_RStudio_remotely">use RStudio in JupyterHub</a></li>
<li><a href="https://posit.co/download/rstudio-desktop/">or install RStudio Desktop locally</a>,</li>
</ul>
<p>See <a href="FAQ.html">FAQ</a> for frequently asked questions about R problems in this course. The <a href="demos.html">demo codes</a> provide useful starting points for all the assignments.</p>
<ul>
<li>For learning R programming basics
<ul>
<li><a href="https://r-bootcamp.netlify.app/">R Bootcamp</a> Very short interactive tutorial for ggplot2 and nadling dataframes.</li>
<li><a href="https://rstudio-education.github.io/hopr/">Garrett Grolemund, Hands-On Programming with R</a></li>
</ul></li>
<li>For learning basic and advanced plotting using R
<ul>
<li><a href="https://datavizf24.classes.andrewheiss.com/lesson/">Andrew Heiss, Data Visualiztion with R, Interactive lessons</a></li>
<li><a href="https://rkabacoff.github.io/datavis/index.html">Robert Kabacoff, Modern Data Visualization with R, Online book</a></li>
<li><a href="https://socviz.co/">Kieran Healy, Data Visualization - A practical introduction</a></li>
<li><a href="http://www.gradaanwr.net/">Antony Unwin, Graphical Data Analysis with R</a></li>
</ul></li>
</ul>
</section>
<section id="english-finnish-english-statistics-dictionary" class="level2">
<h2 class="anchored" data-anchor-id="english-finnish-english-statistics-dictionary">English-Finnish-English statistics dictionary</h2>
<p>Excellent online English-Finnish-English statistics dictionary:</p>
<ul>
<li><a href="https://sanasto.tilastoseura.fi/">Juha Alho, Elja Arjas, Esa Läärä ja Pekka Pere (2023). Tilastotieteen sanasto. Suomen Tilastoseuran julkaisuja no. 8. 2. laitos. Suomen Tilastoseura. Helsinki. https://sanasto.tilastoseura.fi/</a></li>
</ul>
<p>Shorter English-Finnish dictionary for the terms specific for this course</p>
<ul>
<li><a href="extra_reading/sanasto.pdf">Lyhyt englanti-suomi sanasto kurssin termeistä</a></li>
</ul>
<p>Sanasta “bayesilainen” esiintyy Suomessa muutamaa erilaista kirjoitustapaa. Olen käyttänyt muotoa “bayesilainen”, joka on muodostettu yleisen vieraskielisten nimien taivutussääntöjen mukaan: <em>“Jos nimi on kirjoitettuna takavokaalinen mutta äännettynä etuvokaalinen, kirjoitetaan päätteseen tavallisesti takavokaali etuvokaalin sijasta, esim. Birminghamissa, Thamesilla.” Terho Itkonen, Kieliopas, 6. painos, Kirjayhtymä, 1997.</em></p>
<p>Suomen tilastoseura sen sijaan suosittaa muotoa “bayseiläinen”. Heidän perustelunsa löytyy Tilastotieteen sanastosta (ks. linkki yllä). Tilastotieteen sanaston verkkoversiossa on hakutoiminto, ja PDF-versio sisältää käännösten perusteluita sekä hieman tilastotieteen varhaista historiaa Suomessa.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/avehtari\.github\.io\/BDA_course_Aalto\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>