---
title: "Bayesian Data Analysis course - Project work"
date: "Page updated: `r format.Date(file.mtime('project.Rmd'),'%Y-%m-%d')`"
---

## Project work report rubric 2024

For the questions having answer scale from 1 to 5, the explanations are for scores 1, 2, 4, and 5, but you can use also score 3.

#### Q1: Can you open the pdf/html-file and it's not essentially empty? If the submission is empty or no-effort nonsense contact the course staff.

- Yes
- No

#### Q2: Is there an introduction?

- 1 = There is no clear introduction;
- 2 = Description is only provided for data/analysis but not both;
- 4 = A brief description is given for both;
- 5 = Description is relevant, detailed, and provides convincing motivation for the project

#### Q3: What are your suggestions on how to improve the introduction?

Enter free text. Comment required.

#### Q4: Is there a description of the data and the analysis problem?

- 1 = There is no clear description;
- 2 = Description is only provided for data/analysis but not both;
- 4 = A brief description is given for both;
- 5 = Description is relevant, detailed, and provides convincing motivation for the project

#### Q5: Did you get a sense of what the data is and the analysis problem is when they were first introduced? Where and how might the author make the model description clearer?

Enter free text. Comment required.

#### Q6: Are there descriptions of at least two models?

- 1 = No, practically non-existing, or nonsense;
- 2 = Only one model described;
- 4 = At least two models described;
- 5 = All (2+) model descriptions are clearly presented and are reasonable choices for the reported analysis problem

#### Q7: Did you get a sense of what the models are? Where and how might the author(s) make the model description clearer?

Enter free text. Comment required.

#### Q8: Are there descriptions and justifications of the prior choices? It is fine to use default brms priors if they are proper (i.e. not for b coefficients)

- 1 = No priors specified, non-existing description, or nonsense;
- 2 = Priors listed and described;
- 4 = Priors are listed and described. The choice of priors is justified and clearly explained;
- 5 = Prior choices show additional background research into subject matter or modelling problem, are justified, and clearly explained

#### Q9: Did you get a sense of what the priors are? Where and how might the author(s) make the prior description and justification clearer?

Enter free text. Comment required.

#### Q10: Is Stan, rstanarm, or brms model code/formula included? The main report can also show parts of a long code, and the complete model code can be in the appendix if it's mentioned in the main text.

- 1 = No model code or nonsense code;
- 2 = Model code included, but it's really messy;
- 4 = Model code included with easy to read layout (even if it would be complex to understand);
- 5 = Model code is clean and obviously optimized for readability

#### Q11: Is there code to show how the model was run so that it's easy to see what options were used?

- Yes
- No, it's practically non-existing, or it's nonsense

#### Q12: Is Rhat convergence diagnostics and interpretation included?

- 1 = No;
- 2 = Yes, but not for all models;
- 4 = Yes, they are provided for all models but no discussion on what can be concluded;
- 5 = Yes, they are provided for all models, with discussion about what can be concluded

#### Q13: Are HMC specific convergence diagnostics (divergences, tree depth) with interpretation of the results included?

- 1 = No;
- 2 = Yes, but not for all models;
- 4 = Yes, they are shown for all models but no discussion on what can be concluded;
- 5 = Yes, they are shown for all models, with discussion about what can be concluded

#### Q14: Are effective sample size diagnostic (usually denoted with n_eff or ESS) and an interpretation of the results included?

- 1 = No;
- 2 = Yes, but not for all models;
- 4 = Yes, they are included for all models but no discussion what can be concluded from the; shown values;
- 5 = Yes, they are included for all models, with discussion what can be concluded from the shown values

#### Q15: Is there posterior predictive checking and interpretation of the results?

- 1 = No;
- 2 = Yes, but not for all models;
- 4 = Yes for all models but no discussion on what can be concluded from the shown checks;
- 5 = Yes for all models, with discussion about what can be concluded from the shown checks


#### Q16 Is there model comparison and interpretation of the results?

- 1 = No;
- 2 = Yes, but not for all models;
- 4 = Yes, but no discussion on what can be concluded from the comparison;
- 5 = Yes, with discussion about what can be concluded from the comparison

#### Q17: Question not available. Skip this.

Due to FeedbackFruits this question is broken, but to keep the original question numbering, we have not deleted this question. Continue to the next question.

#### Q18: Is there prior sensitivity analysis? That is, is there any alternative prior tested  and reported (or power-scaling sensitivity checks conducted) and whether estimates of quantities of interest changed?

- 1 = No;
- 2 = Yes, but not for all models;
- 4 = Yes, but no discussion on what can be concluded from the sensitivity analysis;
- 5 = Yes, with discussion about what can be concluded from the sensitivity analysis

#### Q19: Is there a discussion of problems and potential improvements? The analysis does not need to be perfect. It is ok to have bad models, bad convergence etc, as long as they are acknowledged and discussed.

- 1 = No, practically non-existing, or nonsense;
- 2 = Some;
- 4 = Clear discussion;
- 5 = Clear discussion with relevant, logical, and well-motivated reasons given analysis problem

#### Q20: Is there a conclusion describing what was learned from the data analysis?

- 1 = No, practically non-existing, or nonsense;
- 2 = Conclusion is included;
- 4 = Conclusion is clear;
- 5 = Conclusion is clear and justified given analysis problem

#### Q21: Describe in your own words what is the main conclusion of the data analysis in this report?

Enter free text. Comment required.

#### Q22: Is there a section of self-reflection about what the group learned while making the project?


- There is a self-reflection section
- There is no self-reflection section or it's practically non-existing 

#### Q23: Accuracy of use of statistical terms

- 1 = There are numerous errors in use statistical terms;
- 2 = There are some errors or confusing use of statistical terms;
- 3 = Statistical terms are used accurately (as far as I, the reviewer, know)

#### Q24: Were the numbers reported with reasonable number of digits? (Regardless of which specific convention was chosen)


- Yes, some form of digit/precision control was done
- No, numbers were reported with unnecessary number of digits

#### Q25: Was the amount of code output reasonable (i.e. not excessive and irrelevant to the core analysis being performed) in the report? Putting code output to appendix is acceptable.

- Yes
- No

#### Q26: Was the main body of the report within the 20 page limit? (Not including appendix, table of contents, title page, references)

- Yes
- No

#### Q27: The structure and organization of the report

- 1 = The report lacks a clear data analysis story;
- 2 = The report attempts to tell a coherent data analysis story but lacks some focus and clarity;
- 4 = The report presents a clear cohesive data analysis story;
- 5 = The report presents a clear cohesive data analysis story, which is accessible to any average student on the course

#### Q28: Overall, what did you think of the structure and organization of the report? Name at least one way the author(s) could improve the structure and organization.

Enter free text. Comment required.

#### Q29: Choose something you like about the report and explain why you like it.

Enter free text. Comment required.

#### Q30: For the oral presentation of this work, what improvements or advice would you give to the author(s) that could feasibly be done in time for the presentation?

Enter free text. Comment required.

#### Q31: If you were to go back and redo your own report after reading this submission, what would you change?

Enter free text. Comment required.

#### Q32: If the author(s) were to complete this project work again, what could they change, to make it better?

Enter free text. Comment required.

