---
title: "Bayesian Data Analysis course - Assignments (GSU)"
date: "Page updated: `r format.Date(file.mtime('assignments_gsu.Rmd'),'%Y-%m-%d')`"
---

Bayesian Data Analysis Global South (GSU) 2022

Some TA instructions

Please ask more information and clarifications.

I'll choose the students on 18th February Finland time. I'll email
them with starting instructions.

## Assignments

There are 9 assignments and project.

Assignments are peergraded so you don't need to do grading.

Students can submit to peergrade when they want, but if they submit before the deadlines mentioned in the schedule, then they get their submission peergraded by other students. Each student peergrades 3 other students.

If you want limit your time usage for the course, choose one or more assignments and be active before deadlines for those assignments. Read that assignment and solve it in your mind or even better solve it completely so you know how to help. Instead of assignments you can choose also to focus on answering R, Python or Stan questions.	Add your course slack id in a sheet (link provided in staff channel) so we can see that each assignment gets enough TA love.

## Communication with students

The students are instructed not to send you direct messages (unless you sometimes give a permission to someone). 

There are a separate channels for each assignment, R, Python, and Stan. Students may ask questions in the channels and other students and TAs can answer. If you see good answers by other students or TAs give a thumb up, as I can later collect these and thank active students and TAs. If you notice frequently asked questions it's good to inform me (so I can add it to the course material) and other TAs (so they can find the answer quickly).

In addition of answering questions in general chat, it is very helpful to have sometimes
 - one-on-one slack chat with direct messages to not reveal too much how solve the assignment
 - one-on-one video call with screen sharing etc.
For these there is a #queue channel. You can in self-organized way tell when you would be available for one-on-one questions and then students can in queue channel ask for help and you start answering questions in the queue order. When you start the chat mark the request with talking head emoji, so other TAs know it's being handled. When you finish answering the question mark it with green tick mark so other know it's done. It can be helpful to have some times when more than one TA is handling the queue, but since you are in different time zones I don't know yet how to organize this else than by self organization and some polls for students. If you notice frequently asked questions it's good to inform me (so I can add it to the course material) and other TAs (so they can find the answer quickly).

In addition of answering questions in general chat and one-on-one chats, if there are questions many students would like to hear answers but you think itäs faster by live discussion instead of writing it's possible to also have video calls with several students once.

I also try to have some Q&A sessions on usually confusing topics and make video recordings if there are good new questions.

## Project work

In Aalto course the project work has been only Stan. In this course I
think it's fine to use any common PPL as we have TAs wth experience on
many frameworks. There will be more information on project work later.


