---
title: "Assignment 3"
author: "Aki Vehtari et al."
format: 
  html:
    toc: true
    code-tools: true
    code-line-numbers: true  
    number-sections: true
    mainfont: Georgia, serif
    page-layout: article
editor: source
filters:
  - includes/assignments.lua 
---


# General information

This assignment is related to Lecture 3 and BDA3 Chapters 2 and 3.  Use [Frank Harrell's
recommendations](https://hbiostat.org/blog/post/bayes-freq-stmts/) on
how to state results in Bayesian two group comparisons (and note that
there is no *point null hypothesis testing* in this assignment).

**The maximum amount of points from this assignment is 9.**

We have prepared **two quarto templates specific to this assignment** to help you get started:

- A recommended template ([html](template3.html), [qmd](https://avehtari.github.io/BDA_course_Aalto/assignments/template3.qmd), [pdf](template3.pdf)) which uses some additional packages, 
which however requires a bit more set-up work to run and
- a simple template ([html](simple_template3.html), [qmd](https://avehtari.github.io/BDA_course_Aalto/assignments/simple_template3.qmd), [pdf](simple_template3.pdf)) which doesn't use those additional packages and 
is therefore easier to get to run.

::: {.hint}             
**Reading instructions:** 

- [**The reading instructions for BDA3 Chapter 1**](../BDA3_notes.html#ch2).
- [**The reading instructions for BDA3 Chapter 2**](../BDA3_notes.html#ch3).

{{< include includes/_grading_instructions.md >}}
:::


{{< include includes/_general_info.md >}}

 


# Inference for normal mean and deviation (3 points) 

A factory has a production line for manufacturing car windshields. A
sample of windshields has been taken for testing hardness. 
The observed hardness values $\mathbf{y}_1$ can be found in 
the dataset `windshieldy1` in the `aaltobda` package.

We may assume that the observations follow a normal distribution with an
unknown standard deviation $\sigma$. We wish to obtain information about
the unknown average hardness $\mu$. For simplicity we assume standard
uninformative prior discussed in the book, that is,
$p(\mu, \sigma) \propto \sigma^{-1}$. It is not necessary to derive the
posterior distribution in the report, as it has already been done in the
book (see section 3.2).


::: {.subtask letter=a}
Formulate 

1. the likelihood,
2. the prior, and 
3. the resulting posterior.
:::






::: {.subtask letter=b}
What can you say about the unknown $\mu$?

* Compute and report the point estimate $E(\mu|y)$, 
* compute and report a posterior 95%-interval, 
* plot the density, and
* write interpretation of the result in text.
:::

::: {.hint}
Posterior intervals are also called credible
intervals and are different from confidence intervals. 
:::



::: {.subtask letter=c}
What can you say about the hardness of the next windshield coming
from the production line before actually measuring the hardness?



* Compute and report the point estimate $E(\tilde{y}|y)$, 
* compute and report a posterior **predictive** 95%-interval,
* plot the density, and
* write interpretation of the result in text.
:::

::: {.hint}
Predictive intervals are different from posterior
intervals.

With a conjugate prior a closed form posterior is Student's $t$
form (see equations in the book). 
:::



::: {.rubric}

* Is the source code included?
    * No
    * Yes
* Are the likelihood, prior and the posterior for computing the average hardness value reported? It is ok
to refer to the book instead of deriving the distributions.
    * No
    * Yes, but some are missing
    * Yes
* In part a), were the point estimates and posterior interval provided? (The posterior mean should be
close to **...** and 95% posterior interval should be around **...**)
    * No
    * Yes, but seem incorrect or only one estimate was reported
    * Yes, and the reported values seem plausible
* In part b), was the density plotted?
    * No
    * Yes, but seem incorrect
    * Yes, and the plot seems plausible
* For b)-part, was a formula or a simulation method presented for computing the posterior predictive
distribution? It is ok to refer to the book.
    * No
    * Yes, but seems incorrect
    * Yes
* For c)-part, were the point estimate and predictive interval provided? (95% predictive interval should
be around **...** and the mean the same as in a)-part).
    * No
    * Yes, but seems incorrect
    * Yes, and the reported values seem plausible
* For c)-part, was the density plotted?
    * No
    * Yes, but seems incorrect
    * Yes, and the plot seem plausible

:::

# Inference for the difference between proportions (3 points) 

An experiment was performed to estimate the effect of beta-blockers on
mortality of cardiac patients. A group of patients was randomly assigned
to treatment and control groups: out of 674 patients receiving the
control, 39 died, and out of 680 receiving the treatment, 22 died.
Assume that the outcomes are independent and binomially distributed,
with probabilities of death of $p_0$ and $p_1$ under the control and
treatment, respectively. Set up a noninformative or weakly informative
prior distribution on $(p_0,p_1)$.


::: {.subtask letter=a}
Formulate 

1. the likelihood,
2. the prior, and 
3. the resulting posterior.
:::



::: {.subtask letter=b}
Summarize the posterior distribution for the [odds ratio](https://en.wikipedia.org/wiki/Odds_ratio),
$$
\mathrm{OR} = (p_1/(1-p_1))/(p_0/(1-p_0)).
$$

* Compute and report the point estimate $E(\mathrm{OR}|y_0,y_1)$, 
* compute and report a posterior 95%-interval, 
* plot the histogram, and
* write interpretation of the result in text.

Use [Frank Harrell's recommendations](https://hbiostat.org/blog/post/bayes-freq-stmts/)
how to state results in Bayesian two group comparison.
:::

::: {.hint}
With a conjugate prior, a closed-form posterior is the Beta
form for each group separately (see equations in the book). You can use
`rbeta()` to sample from the posterior distributions of $p_0$ and $p_1$,
and use this sample and odds ratio equation to get a sample from the
distribution of the odds ratio.
:::





::: {.subtask letter=c}
Use at least two different priors, and discuss the sensitivity of
your inference to your choice of prior density with a couple of
sentences.
:::



::: {.rubric}
* Is the source code included?
    * No
    * Yes
* Are the likelihood, prior and the posterior for the death probabilities reported? It is ok to refer to the
book instead of deriving the distributions.
    * No
    * Yes, but some are missing
    * Yes
* In part a), was the simulation algorithm for computing the posterior of the odds ratio presented or
implemented?
    * No
    * Yes, but seems incorrect
    * Yes
* In part a), was the odds ratio summarized with a point estimate and a posterior interval? (The mean
should be close to **...** and 95% posterior interval approximately **...**)
    * No
    * Yes, but results seem incorrect
    * Yes, and the results seem plausible
* In part b), was some discussion about testing alternative priors provided? (For example, one could
have repeated the computations in a)-part with a couple of alternative priors and reported these
results or some related general conclusions briefly)
    * Not at all
    * Some analysis was provided but it was lacking or did not make sense
    * Some alternative priors were tested and some sensible discussion provided
:::

# Inference for the difference between normal means (3 points) 

Consider a case where the same factory has two production lines for
manufacturing car windshields. Independent samples from the two
production lines were tested for hardness. The hardness measurements for
the two samples $\mathbf{y}_1$ and $\mathbf{y}_2$ be found in 
the datasets `windshieldy1` and  `windshieldy2` in the `aaltobda` package.

We assume that the samples have unknown standard deviations $\sigma_1$
and $\sigma_2$. Use uninformative or weakly informative priors and answer the following
questions:



::: {.subtask letter=a}
Formulate 

1. the likelihood,
2. the prior, and 
3. the resulting posterior.
:::



::: {.subtask letter=b}
What can you say about $\mu_d = \mu_1 - \mu_2$?

* Compute and report the point estimate $E(\mu_d|y_1, y_2)$, 
* compute and report a posterior 95%-interval, 
* plot the histogram, and
* write interpretation of the result in text.

Use [Frank Harrell's recommendations](https://hbiostat.org/blog/post/bayes-freq-stmts/)
how to state results in Bayesian two group comparison.
:::

::: {.hint}
With a conjugate prior, a closed-form posterior is Student's
$t$ form for each group separately (see equations in the book). You can
use the `rtnew()` function to sample from the posterior distributions of
$\mu_1$ and $\mu_2$, and use this sample to get a sample from the
distribution of the difference $\mu_d = \mu_1 - \mu_2$.
:::





::: {.subtask letter=c}
Given this specific model, what is the probability that the means
are exactly the same ($\mu_1 = \mu_2$)? Explain your reasoning.
:::


::: {.rubric}

* Is source code included?
    * No
    * Yes
* Are the likelihood, prior and the posterior for the windshield hardness values reported? (It is also ok to
refer to the book or related formulas from exercise 1)
    * No
    * Yes, but some are missing
    * Yes
* In part a), was the simulation algorithm for computing the difference in the means presented or
implemented?
    * No
    * Yes, but seems to be incorrect
    * Yes
* In part a), was the posterior for the difference between the means summarized with point and interval
estimates? (The mean should be close to **...** and 95% posterior interval **...** or something
close to it)
    * No answer
    * Yes, but results seem incorrect or only one estimate was given
    * Yes, and results seem reasonable
* Were some analysis or discussion provided for assessing whether the means could be the same? **...**
    * No analysis or explanation is given
    * Yes, but the analysis or explanation seems incorrect
    * Yes, and the analysis or explanation seems plausible

:::

    

{{< include includes/_overall_quality.md >}}
