---
author: "Aki Vehtari et al."
title: Assignments
format: 
  html:
    toc: true
    code-tools: true
    code-line-numbers: true
    standalone: true
    self-contained: true
    embed-resources: true  
---

## Schedule 2023

The course consists of 12 blocks from February to May 2023. The blocks don't match exactly specific weeks. For example, it's good start reading the material for the next block while making the assignment for one block. There are 9 assignments and a project work with presentation, and thus the assignments are not in one-to-one correspondence with the blocks. The schedule below lists the blocks and how they connect to the topics, book chapters and assignments.

### Schedule overview

Here is an overview of the schedule. Scroll down the page to see detailed instructions for each block. Remember that blocks are overlapping so that when you are working on assignment for one block, you should start watching videos and reading text for the next block.

**Note: All assignment deadlines are on Monday 15:59 UTC+0**


|   | Block                                          | Readings                                                                                                                                                                                                                                                                                              | Lectures                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | Assignment                                                                                                |                                  | Assignment due date |
|---|:-----------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------|----------------------------------|---------------------|
|   | 1. Introduction                                | [BDA3 Chapter 1](chapter_notes/BDA_notes_ch1.pdf)                                                                                                                                                                                                                                                     | [Computational probabilistic modeling](https://www.youtube.com/watch?v=ukE5aqdoLZI), <br> [Introduction to uncertainty and modelling](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=a441a604-ba91-4f51-b88c-af0700b9f2b1), <br> [Introduction to the course contents](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=13fc7889-cfd1-4d99-996c-a9f400f6e5a2)                                                                                                                                                                                                                                  | [Assignment 1 and Rubric questions](assignment1.html) |                                  | 26 February              |
|   | 2. Basics of Bayesian inference                | [BDA3 Chapter 1](chapter_notes/BDA_notes_ch1.pdf), <br> [BDA3 Chapter 2](chapter_notes/BDA_notes_ch2.pdf)                                                                                                                                                                                              | [Lecture 2.1](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=66aa86ca-9346-4f7f-af76-af0e00b9cb83), <br> [Lecture 2.2](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=0b59d2d7-8e48-406c-a51e-af0e00ca3035), <br> Optional: <br> [Extra explanations 2](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=158d119d-8673-4120-8669-ac3900c13304), <br> [Summary 2.1](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=7a297f7d-bb7b-4dd0-9913-a9f500ec822d), <br> [Summary 2.2](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=75b9f18f-e379-4557-a5fa-a9f500f11b40) | [Assignment 2 and Rubric questions](assignment2.html) |                                  | 6 March             |
|   | 3. Multidimensional posterior                  | [BDA3 Chapter 3](chapter_notes/BDA_notes_ch3.pdf)                                                                                                                                                                                                                                                     | [Lecture 3](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=ca0ea8b9-31f0-406d-9d2f-af1600f9826d)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | [Assignment 3 and Rubric questions](assignment3.html) |                                  | 13 March              |
|   | 4. Monte Carlo                                 | [BDA3 Chapter 10](chapter_notes/BDA_notes_ch10.pdf)                                                                                                                                                                                                                                                   | [Lecture 4.1](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=ab7b792b-50ef-42f4-90f5-af1c00b98b48), <br> [Lecture 4.2](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=fe23cc92-4d90-4f68-9148-af1c00e29790)                                                                                                                                                                                                                                                                                                                                                                                  | [Assignment 4](assignment4.pdf), <br> [Rubric questions](assignment4_rubric.html)  |                                  | 20 March              |
|   | 5. Markov chain Monte Carlo                    | [BDA3 Chapter 11](chapter_notes/BDA_notes_ch11.pdf)                                                                                                                                                                                                                                                   | [Lecture 5.1](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=96b8a8a9-60b6-4a7b-bca9-af2300b98547), <br> [Lecture 5.2](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=fdd0c498-4e4a-4586-8ba9-af2300ca712d)                                                                                                                                                                                                                                                                                                                                                                                  | [Assignment 5](assignment5.pdf), <br> [Rubric questions](assignment5_rubric.html)  |                                  | 27 March              |
|   | 6. Stan, HMC, PPL                              | [BDA3 Chapter 12](chapter_notes/BDA_notes_ch12.pdf) + [extra material on Stan](index.html#stan)                                                                                                                                                                                                                 | [Lecture 6.1](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=4cc8f763-ca6a-4f2f-b19c-af2a00ba8eb4), <br>[Lecture 6.2](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=f4eb4269-bb83-49aa-9243-af2a00ccb873)                                                                                                                                                                                                                                                                                                                                                                                   | [Assignment 6](assignment6.pdf), <br> [Rubric questions](assignment6_rubric.html) |                                  | 3 April              |
|   | 7. Hierarchical models and exchangeability     | [BDA3 Chapter 5](chapter_notes/BDA_notes_ch5.pdf)                                                                                                                                                                                                                                                     | [Lecture 7.1](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=6cf678f1-395d-4c91-87c7-af3800da0ff4), <br> [Lecture 7.2](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=2320d64f-1e40-45b0-9b17-af3800c9f435)                                                                                                                                                                                                                                                                                                                                                                                  | [Assignment 7](assignment7.pdf), <br> [Rubric questions](assignment7_rubric.html) |                                  | 17 April            |
|   | 8. Model checking & cross-validation           | [BDA3 Chapter 6](chapter_notes/BDA_notes_ch6.pdf), [BDA3 Chapter 7](chapter_notes/BDA_notes_ch7.pdf), [Visualization in Bayesian workflow](https://doi.org/10.1111/rssa.12378), [Practical Bayesian model evaluation using leave-one-out cross-validation and WAIC](https://arxiv.org/abs/1507.04544) | [Lecture 8.1](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=2c578385-aedc-4657-bc10-af3f00ca3485), <br> [Lecture 8.2](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=f99824f2-2028-43d3-b6c5-af3f00dcafdb)                                                                                                                                                                                                                                                                                                                                                                                  | Start project work                                                                                        |                                  |                 |
|   | 9. Model comparison and selection              | [BDA3 Chapter 7 (not 7.2 and 7.3)](chapter_notes/BDA_notes_ch7.pdf), <br> [Practical Bayesian model evaluation using leave-one-out cross-validation and WAIC](https://arxiv.org/abs/1507.04544)                                                                                                       | [Lecture 9.1](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=a67324b3-dd4d-48f0-8873-af4600cb8fd0), <br> Optional: <br> [Lecture 9.2](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=0649acb6-d782-4667-86db-af4600da8d2f), <br> [Lecture 9.3](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=4b6eeb48-ae64-4860-a8c3-ab0200e40ad8)                                                                                                                                                                                                                                            | [Assignment 8](assignment8.pdf), <br> [Rubric questions](assignment8_rubric.html) |                                  | 24 April              |
|   | 10. Decision analysis                          | [BDA3 Chapter 9](chapter_notes/BDA_notes_ch9.pdf)                                                                                                                                                                                                                                                     | [Lecture 10.1](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=a22aab9c-953c-4ea8-b6ec-af4d00c9fe58)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | [Assignment 9](assignment9.pdf), <br> [Rubric questions](assignment9_rubric.html) |                                  | 8 May            |
|   | 11. Normal approximation, frequency properties | [BDA3 Chapter 4](chapter_notes/BDA_notes_ch4.pdf)                                                                                                                                                                                                                                                     | [Lecture 11.1](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=8cde4d40-1b77-4110-af98-af5400ca38b5), <br> [Lecture 11.2](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=d83f6553-1516-475f-8898-af5400dd7b50)                                                                                                                                                                                                                                                                                                                                                                                |                                                                                                           |                                  |                 |
|   | 12. Extended topics                            | Optional: BDA3 Chapter 8, <br> BDA3 Chapter 14-18, <br> BDA3 Chapter 21                                                                                                                                                                                                                               | Optional: <br> [Lecture 12.1](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=66f5a95d-3288-4338-8b35-af5b00ca9ffc), <br> [Lecture 12.2](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=aa2d2d7e-a762-40e7-9d41-af5b00dd0db9)                                                                                                                                                                                                                                                                                                                                                                 | Project work                                                                                              |                                  | 15 May                |
|   | 13. Project feedback                           |                                                                                                                                                                                                                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | Project feedback                                                                                          |                                  |  22 May             |

